services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MonsieurBiz\SyliusRobotsTxtPlugin\:
        resource: '../src/*'
        exclude: '../src/{Entity}'

    MonsieurBiz\SyliusRobotsTxtPlugin\Controller\:
        resource: '../src/Controller'
        tags: [ 'controller.service_arguments' ]
